#!/bin/sh

export DDS_ROOT=/usr/share/DDS_ROOT
export ACE_ROOT=$DDS_ROOT/ACE_wrappers
export TAO_ROOT=$DDS_ROOT/ACE_wrappers/TAO/
export PERLLIB="$PERLLIB:$DDS_ROOT/tools/scripts/modules"
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$DDS_ROOT/lib"
LOG_LONG="/tmp/opendds_ptest_$(date +%Y%m%d-%H%M%S).log"
LOG_SHORT="/tmp/opendds_ptest_short_$(date +%Y%m%d-%H%M%S).log"

${DDS_ROOT}/tests/auto_run_tests.pl @PTEST_ARGS@ -Config CROSS_COMPILED 2>&1 | tee -a ${LOG_LONG} | sed -rnu '/^auto_run_tests_finished:/p' | sed  -u 's/^auto_run_tests_finished: // ; /Result:0/ s/^/PASS: / ; /Result:0/! s/^/FAIL: /' | sed -u 's/\(.*\) \(Time:.*\) \(Result:.*\)/\1/' | tee -a ${LOG_SHORT}

passed=`grep PASS: ${LOG_SHORT}|wc -l`
failed=`grep FAIL: ${LOG_SHORT}|wc -l`
all=$((passed + failed))

echo "=== Test Summary ==="
echo "TOTAL: ${all}"
echo "PASSED: ${passed}"
echo "FAILED: ${failed}"

exit ${failed}
~
